import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Bot } from 'lucide-react';

interface CodeSummaryProps {
  summary: string;
}

export function CodeSummary({ summary }: CodeSummaryProps) {
  return (
    <Card className="h-full">
      <CardHeader>
        <div className="flex items-start gap-4">
          <div className="p-2 bg-primary/10 rounded-full">
            <Bot className="h-6 w-6 text-primary" />
          </div>
          <div>
            <CardTitle>AI Codebase Summary</CardTitle>
            <CardDescription>An overview generated by AI.</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4 text-sm text-foreground/90">
          {summary.split('\n').map((paragraph, index) => (
            paragraph.trim() && <p key={index}>{paragraph}</p>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
